### ISSUE TITLE
Code review Master Issue

### ISSUE THREAD

**Issue by isabellebowdey** [AGHSEagleRobotics/frc1388-2023#37]
ALL LINE NUMBERS MENTIONED RELEVANT TO COMMIT 774aadd

TO AVOID MESSING UP LINE NUMBERS WHILE DOING THESE TASKS, PLEASE WORK FROM THE BOTTOM OF A CLASS TO THE TOP

This holds all the changes we want to make to our code, based on the code review on 2/18 of commit 774aadd
Update: Sperate tasks made for drive train subsystem, gyro subsystem, constants, robot container, and robot. 

GENERAL NOTES
- [ ] Be consistent with comments! Use comments to explain your code so that other people know what you're doing. Add comments as needed (particularly for complex code). Use "temp" for short-lived lines or comments. use "test" for test code.
- [ ] be consistent in formatting
- [ ] put empty lines after methods
- [ ] when updating a file, feel free to clean up the code! It doesn't matter if you weren't the person who wrote it. 
- [ ] Remove unused imports
- [ ] Make a task to see how fast our robot can go! ft/sec? 
- [ ] Rotational speed too!
- [ ] Auto-indent everything?
- [ ] Keep robot controls document updated with code - and robot map

DRIVE TRAIN SUBSYSTEM NOTES
- Rename driveTrain to driveTrainSubsystem
- line 70-72 in DriveTrain: move configClosedloopRamp lines out of the middle of the left and right config_k lines. It's in a confusing to read spot right now. Coder's discretion but should change. 
- lines 80-83 in DriveTrain: why/how are these lines being used? comment as "test"
- lines 113-119 in DriveTrain: decide what .putNumber 's we want to keep
- delete unneeded comments: line 107, line 112
- line 131 extra ";"
- group encoder stuff together

GYRO SUBSYSTEM NOTES
- clean up 
- we're missing the logging - reincorporate?
- lines 23-26 aren't being used. 
- add dashboard to all gyro constructors
- (there are 3 constructors for each type of gyro)
- KEEP all commented lines from 55 - 75
- optional/coder discretion: change lines 65, 70, 75 to actual comments rather than just commented-out code
- publish to online community?

MULTI CHANNEL GYRO NOTES
- was made by a FIRST team (340?)

CONSTANTS NOTES
- move indent over on 32-35 (parallel with other names)
- review line 45 - is PID_IDX being used? delete if not'
- lines 49-53 need to be cleaned up - proper constant format, make obvious it's controller port
- lines 58 & 59 - rename High and Low speed to something that makes more sense
- put enum Objective in autoConstants
- fix indentation in enum Objective (especially line 78)
- put position enum is autoConstants
- Put brackets on same line as method start
- Width and length lines 127, 128 need to be fixed. Plus, robot length w/bumpers is +3, but width is +6 (3 bumpers)

AUTOMOVE NOTES
- [ ] maybe use internal, motor-based PID loop rather than external? Downside is that it only takes one side

ROBOT CONTAINER NOTES
- clean up beginning of robot container, indent correctly
- lines 72-78 commented out lamdas? We don't want them commented out (76-77 wanted maybe) ((ask calvin))
- The order in which we create subsystems matters
- Use drivetrainsubsystem to pass in only axis(s), not button bindings. Bindings should be in configure button bindings
- fix indentation on switch command for autonomous
- Change position "A", "B", "C" to proper names
- delete lines 191-193 (commented code)
- common on neutral mode method with clarity : rename "set drive train neutral mode"? This is allowing the robot class to access neutral mode

ROBOT NOTES
- lines 46-48 log when every command starts and stops
- Optional: line 67 (checking user button) might want to move to drivetrain periodic. Not needed.
- lines 121-124 asks the auto command "are you done?" but does not do anything with info. Take out

**Comment by isabellebowdey** [comment]
Re-made into these issues
Issues #44 
Issues #43 
Issues #42 
Issues #41 
Issues #40
