### ISSUE TITLE
Competition checklist - stuff to bring

### ISSUE THREAD

**Issue by jtechau** [AGHSEagleRobotics/frc1388-2023#45]
Things to bring:

- [ ] Programming bag:
  - [ ] Programming laptops (2)
  - [x] Mouse (1)
  - [ ] Backup Driver Station laptop
  - [x] Laptop chargers (2)
  - [x] Long ethernet cable for pit
  - [x] Long ethernet cable for practice field
  - [x] USB cable (roboRIO)
  - [x] USB C cable (rev robotics)
  - [x] Xbox controllers  (2)
  - [x] USB drive
  - [x] Velcro cable ties
  - [x] Mouse batteries
