### ISSUE TITLE
Arm Code Review Master Issue

### ISSUE THREAD

**Issue by isabellebowdey** [AGHSEagleRobotics/frc1388-2023#66]
ArmSubsystem
- deleted ArnSetPoint enum, wasn't being used
- deleted commented AnArmPosition code
- deleted PID controller, wasn't working
- switched .setFactoryDefault and .setInverted for primary motor (factory default is first now), as we think .setFactoryDefault was undoing .setInverted
- [ ] setWristMotorPosition (and Arm) - if using, replace magic # (0.5) with constant. Use?
- [ ] for setPrimaryArmMotorPosition, use for auto. returns a boolean

ArmCommand
- made constants for magic numbers
-  deleted commented code

GrabberSubsystem
- got rid of grabber limit switch
- [ ] remove magic number for setGrabberPosition (~line 44)
- changed getGrabberEncoder to m_armGrabberClass.grabberPosition in periodic code
- line 90 - CALVIN!!!!! (deleted)

GrabberCommand
- deleted old commented code
- added a Direction.stopped enum state for when the grabber is not moving
- added a log for grabber direction
- set the grabber motor to 0 and Direction to stopped in end

AutoMovePrimaryArm
- changed isFinished to not return false, but when we want it to end (m_atSetPoint)
- made setPrimaryArmPosition a boolean, command will stop when at setPoint
- [ ] might need to tune deadband of setPrimaryArmPosition, make sure it works correctly

AutoMoveWrist
- [ ] when the encoder isn't changing anymore, end command
- deprecated
- ends right when the deadband is reached
- [ ] deadband for setWristPosition might need tuning
