### ISSUE TITLE
Everything-that-needs-to-work Checklist

### ISSUE THREAD

**Issue by isabellebowdey** [AGHSEagleRobotics/frc1388-2023#67]
- [ ] arm, wrist, grabber moves full range 
- [ ] Grabber retracts when arm reaches "danger zone"
- [ ] arm does not extend past max height (with wrist all the way up)
- [ ] arm can go down even when stopped (for instance, grabber can't pull in because a cube is in the way. Arm is stopped because grabber isn't in enough). 
- [ ] grabber resets on dashboard
- [ ] LEDs

- always make sure there's good code on the robot, and commit + push code when able to
